server.port=8080
spring.application.name=bff-donaton

# URLs de los microservicios (sobrescribir en producción con variables de entorno)
ms.donaciones.url=http://localhost:8081
ms.logistica.url=http://localhost:8082

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
